# OVERVIEW
# This YAML script will attempt to install a Python virtual environment able to
# support the requirements of the Programming Historian tutorial
#
# CONFIGURATION PARAMETERS
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - black 
  - click<8.0
  - cmake<3.20
  - cython
  - descartes
  - ipympl 
  - ipywidgets 
  - jupyterlab_code_formatter # Supports labextension
  - jupyterlab-mathjax3
  - jupyterlab_widgets
  - jupyter-lsp
  - jupyter-lsp-python # Provides LSP Extension + Server
  - lxml
  - mkl-service 
  - nbdime 
  - nltk
  - pandas
  - pyarrow
  - scipy
  - scikit-learn
  - seaborn
  - tabulate  # For exporting from pandas to markdown
  - umap-learn
  - xlrd
  - openpyxl
  - xlsxwriter
  - pip:
    - kneed
    - wordcloud
    - unidecode
