# OVERVIEW
# This YAML script will attempt to install a Python virtual environment able to
# support the requirements of EThOS NLP and PDF processing.
#
# CONFIGURATION PARAMETERS
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - beautifulsoup4 
  - black 
  - bokeh 
  - clustergram 
  - click<8.0
  - cmake<3.20
  - cython
  - dask
  - descartes
  - editdistance
  - enchant # Spell-checker alternative to jamspell: https://www.geeksforgeeks.org/python-spelling-checker-using-enchant/
  - feather-format # Python <-> R data structures
  - gensim
  - geopandas 
  - geopy 
  - hdbscan
  - icecream
  - ipympl 
  - ipyleaflet 
  - ipyparallel 
  - ipywidgets 
  - jupyterlab_code_formatter # Supports labextension
  - jupyterlab-geojson
  - jupyterlab-mathjax3
  - jupyterlab_widgets
  - jupyter-lsp
  - jupyter-lsp-python # Provides LSP Extension + Server
  - legendgram 
  - lxml
  - matplotlib-scalebar
  - mkl-service 
  - nbdime 
  - nltk
  - palettable
  - pandas
  - plotly 
  - polyline 
  - pyspellchecker # https://pypi.org/project/pyspellchecker/
  - qgrid
  - scipy
  - scikit-learn
  - seaborn
  - spacy
  - spacy[transformer]
  - statsmodels
  - tabulate  # For exporting from pandas to markdown
  - textblob
  - tzlocal 
  - umap-learn
  - xlrd
  - openpyxl
  - xlsxwriter
  - pip:
    - boruta # Supports feature selection
    - contractions
    - dtreeviz
    - langdetect
#    - git+https://github.com/alexeyegorov/GuidedLDA # not compiling under mamba
    - jamspell # Needs language model: https://github.com/bakwc/JamSpell#download-models
    - joypy
    - jupytext
    - kneed
    - num2words
    - polyglot
    - python-Levenshtein
    - top2vec
    - wordcloud
    - unidecode
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.0.0/en_core_web_trf-3.0.0-py3-none-any.whl
    - unidecode
